name: first_pipeline
on: push
jobs:
  job1: 
    runs-on: ubuntu-latest
    steps: 
      - name: step1
        run: echo "Hello, Commit happened successfully"
      - name: step3
        run: |
             echo "hello from step3"
             hostname
             pwd
             id
  job2: 
    runs-on: ubuntu-latest
    steps: 
      - name: step1
        run: echo "Hello, from job2, step1"
      - name: step2
        run: | 
          echo "job2 step2"
          sleep 30
      - name: step3
        run: |
          echo "hello from job 2 step3"
          sleep 20
          hostname
          pwd
          id
